# Generated by Django 4.2.30 on 2026-08-17 08:34

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('sku'), models.F('store'), condition=models.Q(('is_active', True)), name='uniq_active_sku_per_store_ci'),
        ),
    ]
