# Generated by Django 4.2.30 on 2026-06-14 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='communicationrequest',
            new_name='communicati_status_74b82d_idx',
            old_name='comm_req_status_next_idx',
        ),
        migrations.RenameIndex(
            model_name='communicationrequest',
            new_name='communicati_communi_96898b_idx',
            old_name='comm_req_type_status_idx',
        ),
    ]
