# --- Trigger codes. Add a constant here for each new event.
LOW_STOCK_ALERT         = 'LOW_STOCK_ALERT'
OUT_OF_STOCK_ALERT      = 'OUT_OF_STOCK_ALERT'
NEW_SALE_RECORDED       = 'NEW_SALE_RECORDED'
SUPPLIER_ORDER_PLACED   = 'SUPPLIER_ORDER_PLACED'
SUPPLIER_ORDER_RECEIVED = 'SUPPLIER_ORDER_RECEIVED'

# --- Auth trigger codes
PASSWORD_RESET = 'PASSWORD_RESET'
WELCOME_EMAIL  = 'WELCOME_EMAIL'

# --- Channel codes
EMAIL_COMMUNICATION              = 'EMAIL'
WHATSAPP_COMMUNICATION           = 'WHATSAPP'
PUSH_NOTIFICATION_COMMUNICATION  = 'PUSH_NOTIFICATION'

CHANNEL_CHOICES = [
    (EMAIL_COMMUNICATION,             'Email'),
    (WHATSAPP_COMMUNICATION,          'WhatsApp'),
    (PUSH_NOTIFICATION_COMMUNICATION, 'Push Notification'),
]

# --- WhatsApp message types
TEXT_MESSAGE     = 'TEXT'
DOCUMENT_MESSAGE = 'DOCUMENT'

# --- Request status (small int)
PENDING_STATUS = 0
STARTED_STATUS = 1
SUCCESS_STATUS = 2
RETRY_STATUS   = 3
FAILURE_STATUS = 4

STATUS_CHOICES = [
    (PENDING_STATUS, 'Pending'),
    (STARTED_STATUS, 'Started'),
    (SUCCESS_STATUS, 'Success'),
    (RETRY_STATUS,   'Retry'),
    (FAILURE_STATUS, 'Failure'),
]

# --- Retry tuning
COMMUNICATION_REQUESTS_RETRIES                  = 3
COMMUNICATION_REQUESTS_RETRY_TIME_IN_MINUTES    = 15
